import Head from 'next/head'
import { useRouter } from 'next/router'
import { GetServerSideProps } from 'next'

import { SearchHeader } from '@/components/go-v3/SearchHeader'

import results from '@/res.js'

export default function SearchPage({ results }: any) {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>{`${router.query.term} - Search`}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <SearchHeader />
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      results,
    },
  }
}
